name: computorbuild
channels:
  - conda-forge
dependencies:
  - r-base=4.1.0
  - r-codetools
  - r-huge
  - r-matrix
  - r-remotes
  - r-reticulate
  - r-rmarkdown
  - r-tidyverse
  - r-devtools
  - r-tinytex
  - r-mvtnorm
  - r-mass
  - r-igraph
  - r-captioner