name: computorbuild
channels:
  - conda-forge
  - r
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - r-base
  - r-knitr
  - r-plotly
  - r-codetools
  - r-huge
  - r-matrix
  - r-remotes
  - r-reticulate
  - r-rmarkdown
  - r-tidyverse
  - r-devtools
  - r-tinytex
  - r-mvtnorm
  - r-mass
  - r-igraph
  - r-captioner