name: computorbuild
channels:
  - conda-forge
  - r
dependencies:
  - jupyter
  - matplotlib
  - numpy == 1.22.4
  - scipy == 1.7.1
  - scikit-learn
  - matplotlib
  - pandas
  - r-base
  - r-knitr
  - r-plotly
  - r-codetools
  - r-huge
  - r-matrix
  - r-remotes
  - r-reticulate
  - r-rmarkdown
  - r-tidyverse
  - r-devtools
  - r-tinytex
  - r-mvtnorm
  - r-mass
  - r-igraph
  - r-testthat
  - r-BiocManager
  - r-igraph
  - r-ggrepel