name: build

on:
  schedule:
    # launch the build weekly to check that everything works find
    - cron:  '0 0 * * 0' 
  push:
    branches:
      - main
      - master

env:
  quarto_file: content
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  computorticle:
    runs-on: macos-latest

    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Installing dependencies with Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: computo
          
      - name: Install additional python dependencies
        run: reticulate::py_install(packages = c("pylearn-parsimony"), envname = "computo", method = "conda", conda = "auto", python_version = 3.8, pip = TRUE, pip_options = 'git+https://github.com/neurospin/pylearn-parsimony.git')

      - name: Install additional R dependencies
        run: | 
          conda run -n computo Rscript r-addons.R
          
      - name: Installing quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        
      - name: Rendering with Quarto
        shell: bash -l {0}
        run: |
            quarto render ${{ env.quarto_file }}.qmd
            mkdir _build
            mv ${{ env.quarto_file }}.html _build/index.html
            cp environment.yml _build/

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build
          CLEAN: true
